export const teamMembers = [
  {
    id: 1,
    name: "Aria Chen",
    role: "Co-Founder & Oracle ACE",
    department: "Leadership",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=aria&backgroundColor=b6e3f4",
    bio: "Oracle ACE Director with 10+ years of database engineering experience. Loves building regional developer ecosystems and coordinating with global speakers.",
    stats: { tickets: "120+", rating: "4.9", response: "< 1hr" },
    color: "#1e0f0f",
  },
  {
    id: 2,
    name: "Olivia Martinez",
    role: "Lead OCI Architect",
    department: "Cloud Tech",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=olivia&backgroundColor=ffd5dc",
    bio: "Specialist in large-scale cloud migrations and high-performance networks. Certified OCI Solutions Architect Professional who guides local startups.",
    stats: { tickets: "85+", rating: "4.8", response: "< 2hr" },
    color: "#1f1012",
  },
  {
    id: 3,
    name: "Richard Mills",
    role: "Database Tuning Expert",
    department: "DB Core",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=richard&backgroundColor=c0aede",
    bio: "Focused on PL/SQL optimization, indexes, and custom diagnostics. Loves debugging execution plans and hosting workshops on database internals.",
    stats: { tickets: "94+", rating: "4.9", response: "< 1.5hr" },
    color: "#160d2b",
  },
  {
    id: 4,
    name: "Viola Bassett",
    role: "Student Corner Lead",
    department: "Community",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=viola&backgroundColor=d1f4e0",
    bio: "Leads our university programs and bootcamps. Coordinates student workshops, hands-on labs, and certification preparation classes in West Bengal.",
    stats: { tickets: "110+", rating: "5.0", response: "< 30min" },
    color: "#0f1e14",
  },
  {
    id: 5,
    name: "Sophie Chamberlain",
    role: "Event Coordinator",
    department: "Events",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sophie&backgroundColor=fde68a",
    bio: "Dedicated to organizing monthly physical meetups, speaker logistics, and community partnership coordination in Kolkata.",
    stats: { tickets: "60+", rating: "4.9", response: "< 2hr" },
    color: "#241e0d",
  },
  {
    id: 6,
    name: "Erik Anders",
    role: "Oracle ACE Associate",
    department: "DB Core",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=erik&backgroundColor=a5f3fc",
    bio: "Experienced DBA hosting database recovery simulations and storage configuration labs. Frequent speaker at local user groups.",
    stats: { tickets: "72+", rating: "4.9", response: "< 1hr" },
    color: "#0d2124",
  },
  {
    id: 7,
    name: "Natalie Carter",
    role: "Content Coordinator",
    department: "Media",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=natalie&backgroundColor=fed7aa",
    bio: "Manages community tech articles, newsletter curation, and training guides. Passionate about sharing useful SQL nuggets.",
    stats: { tickets: "55+", rating: "4.8", response: "< 2hr" },
    color: "#24180d",
  },
  {
    id: 8,
    name: "Marcus Webb",
    role: "OCI DevOps Specialist",
    department: "Cloud Tech",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus&backgroundColor=bbf7d0",
    bio: "Automation engineer focused on Terraform scripting, CI/CD pipelines, and Kubernetes deployment on OKE. Guides developers in serverless architectures.",
    stats: { tickets: "80+", rating: "4.7", response: "< 3hr" },
    color: "#0f1e14",
  },
];